excluded:
  - Pods

disabled_rules:
  - switch_case_alignment
  - identifier_name
  - cyclomatic_complexity

opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping

force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

force_unwrapping:
  severity: warning

line_length: 120

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2